export const moviePosters: Record<string, string> = {
  "A Girl Walks Home Alone at Night": "https://image.tmdb.org/t/p/w500/cd2rCE1nun7CESjBI8PGNEof1tb.jpg",
  "American Sniper": "https://image.tmdb.org/t/p/w500/vJgtfUmZE5i4L12sOryAPuBa04K.jpg",
  "Big Hero 6": "https://image.tmdb.org/t/p/w500/2mxS4wUimwlLmI1xp6QW6NSU361.jpg",
  "Birdman": "https://image.tmdb.org/t/p/w500/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg",
  "Citizenfour": "https://image.tmdb.org/t/p/w500/nOVhX69EAxtSKEEnr5UcSd5UVci.jpg",
  "Fury": "https://image.tmdb.org/t/p/w500/pfte7wdMobMF4CVHuOxyu6oqeeA.jpg",
  "Guardians of the Galaxy": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "Interstellar": "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
  "The Grand Budapest Hotel": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
  "The Imitation Game": "https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
  "The LEGO Movie": "https://image.tmdb.org/t/p/w500/lbctonEnewCYZ4FYoTZhs8cidAl.jpg",
  "The Look of Silence": "https://image.tmdb.org/t/p/w500/7TakQLT8gyzIMG8hX8RLTd5qROQ.jpg",
  "The Normal Heart": "https://image.tmdb.org/t/p/w500/rQwdv1bNdc0OSG8svAEfWACcAAU.jpg",
  "Whiplash": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
  "7 Days in Hell": "https://image.tmdb.org/t/p/w500/fyY19vwlKaJfPJHunvc7fjQczI1.jpg",
  "Amy": "https://image.tmdb.org/t/p/w500/qL0RepWSNUuZoeDXfyhqowVYhrn.jpg",
  "Beasts of No Nation": "https://image.tmdb.org/t/p/w500/1D4vcJmJc58WXarpRtwgd2do9Rg.jpg",
  "Bessie": "https://image.tmdb.org/t/p/w500/kanAZsL3kZwFWRuR6tqLvNrEFco.jpg",
  "Bone Tomahawk": "https://image.tmdb.org/t/p/w500/4MmTHpn2Y8emqvBgvOjufImUmKZ.jpg",
  "Cinderella": "https://image.tmdb.org/t/p/w500/j91LJmcWo16CArFOoapsz84bwxb.jpg",
  "Eye in the Sky": "https://image.tmdb.org/t/p/w500/faRGb9SuyGuZpsNRoIxoVSLLCId.jpg",
  "Inside Out": "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
  "Mad Max: Fury Road": "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
  "Sicario": "https://image.tmdb.org/t/p/w500/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg",
  "Slow West": "https://image.tmdb.org/t/p/w500/j3PmbRZvf5KpNbapSjn8b0CpD6a.jpg",
  "Straight Outta Compton": "https://image.tmdb.org/t/p/w500/1CiLJx8Xtv3TbbFj6k7BboSmKgC.jpg",
  "The Big Short": "https://image.tmdb.org/t/p/w500/scVEaJEwP8zUix8vgmMoJJ9Nq0w.jpg",
  "The Hateful Eight": "https://image.tmdb.org/t/p/w500/jIywvdPjia2t3eKYbjVTcwBQlG8.jpg",
  "The Martian": "https://image.tmdb.org/t/p/w500/fASz8A0yFE3QB6LgGoOfwvFSseV.jpg",
  "The Revenant": "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
  "13th": "https://image.tmdb.org/t/p/w500/uGGpnWHOmWTARVN9wbC1nPxNgps.jpg",
  "All the Way": "https://image.tmdb.org/t/p/w500/j4AEurmnYoRsA1nHhRK9AE4j2CL.jpg",
  "Arrival": "https://image.tmdb.org/t/p/w500/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
  "Confirmation": "https://image.tmdb.org/t/p/w500/9lxg4KidKhRAMupBYvgdHxAnxKE.jpg",
  "Hacksaw Ridge": "https://image.tmdb.org/t/p/w500/fnOMP6mjmOmZwmlC1n0K7ivrzt1.jpg",
  "Hell or High Water": "https://image.tmdb.org/t/p/w500/ljRRxqy2aXIkIBXLmOVifcOR021.jpg",
  "In a Valley of Violence": "https://image.tmdb.org/t/p/w500/otuBE30CGhmIUznkX0AwkAQerMF.jpg",
  "Kubo and the Two Strings": "https://image.tmdb.org/t/p/w500/ewcOCkuuKAKULGUnbBVaO1htt0D.jpg",
  "La La Land": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  "Moana": "https://image.tmdb.org/t/p/w500/9tzN8sPbyod2dsa0lwuvrwBDWra.jpg",
  "O.J.: Made in America": "https://image.tmdb.org/t/p/w500/2FW1ViDhIShRpjQx8isstiB6jel.jpg",
  "Pete's Dragon": "https://image.tmdb.org/t/p/w500/A9x4Ogk8KUXTfU649NS6lS9TCmu.jpg",
  "Silence": "https://image.tmdb.org/t/p/w500/x5T0cQDYws0xRBVG4Q3wpcrcmax.jpg",
  "Sing": "https://image.tmdb.org/t/p/w500/rwopfpHqPCYBSgBuZwkaXXqHp14.jpg",
  "The BFG": "https://image.tmdb.org/t/p/w500/w17Mc2x2olB5CtewznUFxgpvne0.jpg",
  "The Magnificent Seven": "https://image.tmdb.org/t/p/w500/ezcS78TIjgr85pVdaPDd2rSPVNs.jpg",
  "The Nice Guys": "https://image.tmdb.org/t/p/w500/clq4So9spa9cXk3MZy2iMdqkxP2.jpg",
  "Train to Busan": "https://image.tmdb.org/t/p/w500/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg",
  "Your Name": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
  "Beauty and the Beast": "https://image.tmdb.org/t/p/w500/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg",
  "Blade Runner 2049": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
  "Coco": "https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
  "Dunkirk": "https://image.tmdb.org/t/p/w500/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
  "Get Out": "https://image.tmdb.org/t/p/w500/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
  "Hostiles": "https://image.tmdb.org/t/p/w500/rqoezyB51GfhiloOB5ZErg5HXas.jpg",
  "Icarus": "https://image.tmdb.org/t/p/w500/x5azMi1KvZWbBbfjmGqpHNGqjH.jpg",
  "Logan": "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
  "The 12th Man": "https://image.tmdb.org/t/p/w500/dxZ8iGf5jQoLcNqBJL6uzNTivp.jpg",
  "The Immortal Life of Henrietta Lacks": "https://image.tmdb.org/t/p/w500/njFJjXhK94NXAxo9MJrskFpqWMg.jpg",
  "The Shape of Water": "https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
  "The Wizard of Lies": "https://image.tmdb.org/t/p/w500/8k4lJ4e0hvDQtKpItXmmPdw69sO.jpg",
  "Wind River": "https://image.tmdb.org/t/p/w500/pySivdR845Hom4u4T2WNkJxe6Ad.jpg",
  "12 Strong": "https://image.tmdb.org/t/p/w500/37Qwani2g0jVPU7N4OkkTZ7aERz.jpg",
  "A Quiet Place": "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
  "Avengers: Infinity War": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "Black Panther": "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  "Bohemian Rhapsody": "https://image.tmdb.org/t/p/w500/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
  "Fahrenheit 451": "https://image.tmdb.org/t/p/w500/urH9H50gKbUK8U6qTVd89SLQPjx.jpg",
  "Free Solo": "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
  "Hereditary": "https://image.tmdb.org/t/p/w500/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg",
  "Minding the Gap": "https://image.tmdb.org/t/p/w500/uOu2YgrryHD1UlngykzTodAxGdC.jpg",
  "Roma": "https://image.tmdb.org/t/p/w500/dtIIyQyALk57ko5bjac7hi01YQ.jpg",
  "Spider-Man: Into the Spider-Verse": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
  "The Ballad of Buster Scruggs": "https://image.tmdb.org/t/p/w500/voxl654m7p36y8FLu8oQD7dfwwK.jpg",
  "The Favourite": "https://image.tmdb.org/t/p/w500/cwBq0onfmeilU5xgqNNjJAMPfpw.jpg",
  "They Shall Not Grow Old": "https://image.tmdb.org/t/p/w500/yMGfJeTXUdIjOqjS0jJfjgYEuYC.jpg",
  "Won't You Be My Neighbor?": "https://image.tmdb.org/t/p/w500/8qE8NZjiP2M884baH0VoLF828Vp.jpg",
  "One Piece Film: Red": "https://image.tmdb.org/t/p/w500/8ibfhe4P7rhmn3lrPhOZzIJHA2B.jpg",
  "One Piece: Stampede": "https://image.tmdb.org/t/p/w500/4E2lyUGLEr3yH4q6kJxPkQUhX7n.jpg",
  "One Piece Film: Gold": "https://image.tmdb.org/t/p/w500/9PgiOFTLZXP7emlwcIt0yRasJ9h.jpg",
};
